import {UNIT_TYPES, STARTING_SQUAD} from '../data/units.js';
import {ENEMY_TYPES} from '../data/enemies.js';
import {ARTIFACTS} from '../data/artifacts.js';
import {LEVELS,WAVE_ARCHETYPES} from '../data/levels.js';
import {BOSSES} from '../data/bosses.js';
import {RNG} from './random.js';

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const dist2=(a,b)=>{const x=a.x-b.x,y=a.y-b.y;return x*x+y*y};

export class Game {
 constructor(canvas,audio,ui){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.audio=audio;this.ui=ui;this.inputX=0;this.running=false;this.paused=false;this.choiceOpen=false;this.mode='campaign';this.levelIndex=0;this.last=0;this.acc=0;this.fixed=1/60;this.resize();window.addEventListener('resize',()=>this.resize())}
 resize(){const dpr=Math.min(devicePixelRatio||1,2);this.w=innerWidth;this.h=innerHeight;this.canvas.width=this.w*dpr;this.canvas.height=this.h*dpr;this.canvas.style.width=this.w+'px';this.canvas.style.height=this.h+'px';this.ctx.setTransform(dpr,0,0,dpr,0,0)}
 defaultMods(){return {damage:1,fireRate:1,damageTaken:1,maxHp:1,regen:0,pierce:0,ricochet:0,burnChance:0,burnDuration:2.5,burnSlow:false,slowChance:0,recruit:1,bossDamage:1,killExplosion:0,stormEvery:0,overdrive:false,shrapnel:false,chainReaction:false,aegis:false,commandNet:false,chainDamage:1,lastStand:false,armageddon:0,quantum:0,phoenix:0}}
 start(levelIndex=0,mode='campaign'){this.audio.unlock();this.mode=mode;this.levelIndex=levelIndex;this.rng=new RNG((levelIndex+1)*99173+(mode==='endless'?777:0));this.state={time:0,kills:0,hits:0,eventIndex:0,eventTime:0,eventSpawned:0,eventDone:false,startedAt:performance.now(),artifacts:[],mods:this.defaultMods(),units:[],enemies:[],effects:[],projectiles:[],bosses:[],deadTroops:0,abilityCd:0,abilityActive:0,aegisTimer:20,aegisShield:0,lastStandUsed:false,majorEncounter:0,endlessWave:0,totalDamage:0};STARTING_SQUAD.forEach(t=>this.addUnit(t));this.running=true;this.paused=false;this.choiceOpen=false;this.ui.showGame();this.beginEvent();this.last=performance.now();requestAnimationFrame(t=>this.frame(t))}
 currentLevel(){if(this.mode==='endless')return this.makeEndlessLevel();return LEVELS[Math.min(this.levelIndex,LEVELS.length-1)]}
 makeEndlessLevel(){const n=this.state?.endlessWave||0;const archetypes=Object.keys(WAVE_ARCHETYPES);return {name:'Endless',biome:['city','wasteland','hive','machine'][Math.floor(n/4)%4],events:[{type:'wave',label:`WAVE ${n+1}`,kind:archetypes[n%archetypes.length],budget:45+n*13,duration:22+Math.min(10,n*.25)},{type:'reward',kind:n%3===2?'artifact':'reinforce',options:[{unit:'rifleman',count:4+Math.floor(n/4)},{unit:['smg','shotgun','machinegun','grenadier','sniper','tesla','rocket'][n%7],count:2+Math.floor(n/8)}]},{type:'boss',id:Object.keys(BOSSES)[Math.floor(n/5)%Object.keys(BOSSES).length]}]}}
 addUnit(type){const d=UNIT_TYPES[type],idx=this.state.units.length,cols=Math.max(4,Math.ceil(Math.sqrt(idx+1)*1.5)),row=Math.floor(idx/cols),col=idx%cols;this.state.units.push({id:Math.random(),type,hp:d.hp*this.state.mods.maxHp,maxHp:d.hp*this.state.mods.maxHp,cooldown:this.rng.range(0,.5),healCd:this.rng.range(0,1),x:this.w/2+(col-(cols-1)/2)*18,y:this.h-92-row*18,tx:0,ty:0})}
 addTroops(type,count){count=Math.max(1,Math.round(count*this.state.mods.recruit));for(let i=0;i<count;i++)this.addUnit(type);this.audio.pickup();this.flash(`+${count} ${UNIT_TYPES[type].name.toUpperCase()}`)}
 beginEvent(){const level=this.currentLevel(),ev=level.events[this.state.eventIndex];if(!ev){if(this.mode==='endless'){this.state.endlessWave++;this.state.eventIndex=0;this.beginEvent();return}this.win();return}this.state.eventTime=0;this.state.eventSpawned=0;this.state.eventDone=false;this.state.majorEncounter++;if(this.state.mods.phoenix&&this.state.deadTroops>0&&(ev.type==='elite'||ev.type==='boss')){const n=Math.min(this.state.mods.phoenix,this.state.deadTroops);for(let i=0;i<n;i++)this.addUnit('rifleman');this.state.deadTroops-=n;this.flash(`PHOENIX +${n}`)}if(ev.type==='reward'){setTimeout(()=>this.openReward(ev),150);return}if(ev.type==='boss'){this.spawnBoss(ev.id);this.flash(BOSSES[ev.id].name);return}this.flash(ev.label||'WAVE')}
 advanceEvent(){this.state.eventIndex++;this.beginEvent()}
 openReward(ev){this.choiceOpen=true;this.paused=true;if(ev.kind==='artifact'){const pool=this.rng.shuffle(ARTIFACTS.filter(a=>!this.state.artifacts.includes(a.id))).slice(0,3);this.ui.openChoice('ARTIFACT CACHE','Choose one artifact',pool.map(a=>({name:a.name,kicker:a.rarity,description:a.description,tag:a.tag,onPick:()=>{a.apply(this.state);this.state.artifacts.push(a.id);this.closeChoice()}})));return}if(ev.kind==='crate'){const options=[{unit:'machinegun',count:2},{unit:'grenadier',count:2},{unit:'shotgun',count:3}];this.ui.openChoice('WEAPON CRATE','Arm the squad',options.map(o=>({name:`+${o.count} ${UNIT_TYPES[o.unit].name}`,kicker:'WEAPON TEAM',description:`Adds ${UNIT_TYPES[o.unit].role} specialists to the formation.`,tag:'RECRUIT',onPick:()=>{this.addTroops(o.unit,o.count);this.closeChoice()}})));return}const options=ev.options||[{unit:'rifleman',count:5},{unit:'smg',count:3}];this.ui.openChoice(ev.kind==='rescue'?'RESCUE POD':'REINFORCEMENT','Choose your reinforcement',options.map(o=>({name:`+${o.count} ${UNIT_TYPES[o.unit].name}`,kicker:ev.kind==='rescue'?'RESCUE':'RECRUIT',description:`${UNIT_TYPES[o.unit].role}.`,tag:'ADD TROOPS',onPick:()=>{this.addTroops(o.unit,o.count);this.closeChoice()}})))}
 closeChoice(){this.choiceOpen=false;this.paused=false;this.ui.closeChoice();this.advanceEvent();this.last=performance.now()}
 spawnEnemy(type,x=null,y=-30,scale=1){const d=ENEMY_TYPES[type];this.state.enemies.push({id:Math.random(),type,x:x??this.rng.range(30,this.w-30),y,hp:d.hp*scale,maxHp:d.hp*scale,speed:d.speed*(1+Math.min(.35,this.levelIndex*.018)),radius:d.radius,attackCd:0,healCd:0,summonCd:this.rng.range(1,3),burn:0,burnDps:0,slow:0,scale,dead:false})}
 spawnFromWave(ev,dt){const budget=ev.budget*(1+this.levelIndex*.045),target=Math.floor(budget);const rate=Math.max(1.6,target/ev.duration);this.state.eventSpawned+=rate*dt;while(this.state.eventSpawned>=1&&this.state.eventTime<ev.duration){this.state.eventSpawned-=1;const kind=this.rng.weighted(WAVE_ARCHETYPES[ev.kind]||WAVE_ARCHETYPES.mixed);this.spawnEnemy(kind);}}
 spawnBoss(id){const d=BOSSES[id];const hp=d.hp*(1+this.levelIndex*.12+(this.mode==='endless'?this.state.endlessWave*.08:0));const base={id:Math.random(),type:'boss',bossId:id,x:this.w/2,y:86,hp,maxHp:hp,radius:d.radius,speed:d.speed,damage:d.damage,armor:d.armor||0,pattern:d.pattern,t:0,phase:1,attackCd:1.5,summonCd:2.5,targetX:this.w/2,hidden:false,enraged:false};this.state.bosses.push(base);if(id==='twins'){base.hp=base.maxHp=hp*.62;base.x=this.w*.35;this.state.bosses.push({...base,id:Math.random(),x:this.w*.65,hp:hp*.62,maxHp:hp*.62,t:0})}}
 frame(now){if(!this.running)return;const dt=Math.min(.05,(now-this.last)/1000||0);this.last=now;if(!this.paused){this.acc+=dt;while(this.acc>=this.fixed){this.update(this.fixed);this.acc-=this.fixed}}this.render();this.ui.updateHud(this);requestAnimationFrame(t=>this.frame(t))}
 update(dt){const s=this.state;s.time+=dt;s.eventTime+=dt;s.abilityCd=Math.max(0,s.abilityCd-dt);s.abilityActive=Math.max(0,s.abilityActive-dt);if(s.mods.aegis){s.aegisTimer-=dt;if(s.aegisTimer<=0){s.aegisShield=.22;s.aegisTimer=20;this.flash('AEGIS SHIELD')}}const ev=this.currentLevel().events[s.eventIndex];if(ev&&(ev.type==='wave'||ev.type==='elite')){this.spawnFromWave(ev,dt);if(s.eventTime>ev.duration&&s.enemies.length===0)this.advanceEvent()}this.updateUnits(dt);this.updateEnemies(dt);this.updateBosses(dt);this.updateProjectiles(dt);this.updateEffects(dt);this.cleanup();if(s.units.length===0)this.lose()}
 formationTarget(i,n){const cols=Math.min(11,Math.max(4,Math.ceil(Math.sqrt(n)*1.45))),row=Math.floor(i/cols),col=i%cols;const spacing=Math.max(12,Math.min(20,250/cols));return {x:this.w/2+this.inputX*(this.w*.34)+(col-(Math.min(cols,n-row*cols)-1)/2)*spacing,y:this.h-82-row*16}}
 updateUnits(dt){const s=this.state,alive=s.units;let totalHp=0,totalMax=0;for(let i=0;i<alive.length;i++){const u=alive[i],d=UNIT_TYPES[u.type],target=this.formationTarget(i,alive.length);u.x+=(target.x-u.x)*Math.min(1,dt*8);u.y+=(target.y-u.y)*Math.min(1,dt*8);totalHp+=u.hp;totalMax+=u.maxHp;if(s.mods.regen)u.hp=Math.min(u.maxHp,u.hp+u.maxHp*s.mods.regen*dt);u.cooldown-=dt;u.healCd-=dt;if(d.heal&&u.healCd<=0){const wounded=alive.filter(a=>a.hp<a.maxHp).sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp)[0];if(wounded)wounded.hp=Math.min(wounded.maxHp,wounded.hp+d.heal);u.healCd=1/d.healRate}let fireRate=d.fireRate*s.mods.fireRate;if(s.abilityActive>0)fireRate*=1.65;if(s.mods.overdrive&&totalMax&&totalHp/totalMax<.35)fireRate*=1.7;const targetEnemy=this.pickTarget(u,d.range);if(targetEnemy&&u.cooldown<=0){this.fire(u,targetEnemy,d);u.cooldown=1/fireRate}}}
 pickTarget(u,range){let best=null,bestD=range*range;for(const e of [...this.state.enemies,...this.state.bosses]){if(e.hidden)continue;const dd=dist2(u,e);if(dd<bestD){best=e;bestD=dd}}return best}
 fire(u,target,d){const s=this.state;s.hits++;const dmg=d.damage*s.mods.damage*(target.type==='boss'?s.mods.bossDamage:1);if(d.projectile==='grenade'||d.projectile==='rocket'){s.projectiles.push({x:u.x,y:u.y,tx:target.x,ty:target.y,target,dmg,splash:d.splash||0,t:0,duration:d.projectile==='rocket'?.22:.36,kind:d.projectile,color:d.color});this.audio.shot(d.projectile)}else if(d.projectile==='tesla'){this.hit(target,dmg,0);this.chain(target,dmg*.62*s.mods.chainDamage,d.chains||3);s.effects.push({type:'beam',x:u.x,y:u.y,x2:target.x,y2:target.y,t:.12,color:d.color})}else{const pellets=d.pellets||1;for(let p=0;p<pellets;p++){const mult=pellets>1?.72:1;this.hit(target,dmg*mult,d.armorPierce||0);if(s.mods.ricochet&&this.rng.next()<s.mods.ricochet)this.chain(target,dmg*.55*s.mods.chainDamage,1);if(s.mods.burnChance&&this.rng.next()<s.mods.burnChance){target.burn=s.mods.burnDuration;target.burnDps=Math.max(target.burnDps,dmg*.22)}if(s.mods.slowChance&&this.rng.next()<s.mods.slowChance)target.slow=1.5;s.effects.push({type:'tracer',x:u.x+(p-pellets/2)*2,y:u.y,x2:target.x+(p-pellets/2)*7,y2:target.y,t:.08,color:d.color})}this.audio.shot(d.projectile)}if(s.mods.stormEvery&&s.hits%s.mods.stormEvery===0)this.storm(target);if(s.mods.quantum&&s.hits%s.mods.quantum===0)this.hit(target,dmg*.8,0)}
 hit(target,dmg,pierce=0){const armor=Math.max(0,(target.armor??ENEMY_TYPES[target.type]?.armor??0)-pierce);target.hp-=dmg*(1-armor);this.state.totalDamage+=dmg*(1-armor)}
 chain(origin,dmg,count){let cur=origin;for(let i=0;i<count;i++){let next=null,best=130*130;for(const e of this.state.enemies){if(e===cur||e.dead)continue;const d=dist2(cur,e);if(d<best){next=e;best=d}}if(!next)break;this.hit(next,dmg,0);this.state.effects.push({type:'beam',x:cur.x,y:cur.y,x2:next.x,y2:next.y,t:.1,color:'#69e9ff'});cur=next}}
 storm(origin){this.chain(origin,36*this.state.mods.damage*this.state.mods.chainDamage,6);this.flash('CHAIN LIGHTNING')}
 updateEnemies(dt){const s=this.state;const cx=this.w/2+this.inputX*(this.w*.34),frontY=Math.min(...s.units.map(u=>u.y),this.h-80);for(const e of s.enemies){const d=ENEMY_TYPES[e.type];if(e.burn>0){e.burn-=dt;this.hit(e,e.burnDps*dt,0);if(s.mods.burnSlow)e.slow=Math.max(e.slow,.3)}if(e.slow>0)e.slow-=dt;if(d.heal){e.healCd-=dt;if(e.healCd<=0){for(const a of s.enemies)if(dist2(e,a)<95*95)a.hp=Math.min(a.maxHp,a.hp+d.heal);e.healCd=d.healRate}}if(d.summon){e.summonCd-=dt;if(e.summonCd<=0){for(let i=0;i<3;i++)this.spawnEnemy(d.summon,e.x+this.rng.range(-25,25),e.y+this.rng.range(-15,15),.8);e.summonCd=d.summonRate}}let targetY=frontY;let speed=e.speed*(e.slow>0?.58:1);if(d.ranged&&frontY-e.y<d.ranged){e.attackCd-=dt;if(e.attackCd<=0){this.damageArmy(d.damage);e.attackCd=1/d.fireRate}}else{const steer=(cx-e.x)*.7;e.x+=clamp(steer,-speed*.55,speed*.55)*dt;e.y+=speed*dt}if(e.y>frontY-7){if(d.explode){this.damageArmy(d.damage);this.explosion(e.x,e.y,d.explode,d.damage*.6,true);e.hp=0}else{e.attackCd-=dt;if(e.attackCd<=0){this.damageArmy(d.damage);e.attackCd=.85}}}}}
 damageArmy(amount){const s=this.state;if(s.aegisShield>0){amount*=1-s.aegisShield;s.aegisShield=Math.max(0,s.aegisShield-.025)}amount*=s.mods.damageTaken;const targets=[...s.units].sort((a,b)=>a.y-b.y).slice(0,Math.max(1,Math.ceil(s.units.length*.12)));if(!targets.length)return;const each=amount/targets.length;for(const u of targets)u.hp-=each}
 updateBosses(dt){for(const b of this.state.bosses){const d=BOSSES[b.bossId];b.t+=dt;b.attackCd-=dt;b.summonCd-=dt;const hp=b.hp/b.maxHp;b.phase=hp>.66?1:hp>.33?2:3;const cx=this.w/2+this.inputX*this.w*.34,frontY=Math.min(...this.state.units.map(u=>u.y),this.h-80);switch(b.pattern){case'brute':b.y+=b.speed*(b.phase===3?1.5:1)*dt;if(b.attackCd<=0&&b.y>frontY-210){b.y+=55;b.attackCd=2.6;this.flash('BRUTE CHARGE')}break;case'tank':b.y+=b.speed*dt;b.armor=(Math.sin(b.t*1.8)>.55)?.08:.52;if(b.armor<.2&&Math.sin(b.t*1.8)>.55)this.state.effects.push({type:'ring',x:b.x,y:b.y,r:46,t:.12,color:'#ffe66d'});break;case'brood':b.y+=b.speed*.5*dt;if(b.summonCd<=0){for(let i=0;i<5+b.phase*2;i++)this.spawnEnemy('swarmer',b.x+this.rng.range(-80,80),b.y+30,.9);b.summonCd=3.5-b.phase*.5}break;case'general':b.y+=b.speed*.38*dt;if(b.summonCd<=0){['shield','grunt','medic','commander'].forEach((t,i)=>this.spawnEnemy(t,b.x+(i-1.5)*40,b.y+35));b.summonCd=4.4-b.phase*.5}break;case'walker':b.y+=b.speed*.25*dt;if(b.attackCd<=0){const x=this.rng.range(45,this.w-45);this.state.effects.push({type:'danger',x,y:frontY,r:50,t:1.2,damage:d.damage});b.attackCd=2.4-b.phase*.3}break;case'twins':b.x+=Math.sin(b.t*1.3+(b.x>this.w/2?2:0))*24*dt;b.y+=b.speed*.42*dt;if(this.state.bosses.length===1)b.enraged=true;if(b.enraged){b.speed=d.speed*1.6;b.damage=d.damage*1.45}break;case'worm':{const cyc=b.t%4.5;b.hidden=cyc<1.6;if(b.hidden){b.x+=((cx+Math.sin(b.t)*110)-b.x)*dt;b.y+=(frontY-130-b.y)*dt}else{b.y+=b.speed*dt;if(cyc>3.6)b.y-=b.speed*2.2*dt}}break;case'carrier':b.x=this.w/2+Math.sin(b.t*.65)*this.w*.28;b.y=90;if(b.summonCd<=0){for(let i=0;i<4+b.phase;i++)this.spawnEnemy(i%3===0?'jammer':'runner',b.x+this.rng.range(-100,100),b.y+30);b.summonCd=4}if(b.attackCd<=0){const x=cx+this.rng.range(-80,80);this.state.effects.push({type:'danger',x,y:frontY,r:58,t:1,damage:d.damage});b.attackCd=2.1}break;case'necro':b.y+=b.speed*.3*dt;if(b.summonCd<=0){for(let i=0;i<Math.min(10,3+b.phase*2);i++)this.spawnEnemy('swarmer',this.rng.range(30,this.w-30),b.y+40,.95);b.summonCd=3.2}break;case'warlord':if(b.phase===1){b.y+=b.speed*.6*dt;if(b.summonCd<=0){for(let i=0;i<6;i++)this.spawnEnemy(i%2?'shield':'runner',b.x+this.rng.range(-90,90),b.y+35);b.summonCd=4}}else if(b.phase===2){b.x=this.w/2+Math.sin(b.t*1.2)*this.w*.28;if(b.attackCd<=0){this.state.effects.push({type:'danger',x:cx,y:frontY,r:65,t:.9,damage:d.damage});b.attackCd=1.8}}else{b.y+=b.speed*1.05*dt;if(b.summonCd<=0){for(let i=0;i<8;i++)this.spawnEnemy('swarmer',this.rng.range(20,this.w-20),b.y+25,1.1);b.summonCd=2.2}}break}if(!b.hidden&&b.y>frontY-10){b.attackCd-=dt;if(b.attackCd<=0){this.damageArmy(b.damage);b.attackCd=1.2}}}}
 updateProjectiles(dt){for(const p of this.state.projectiles){p.t+=dt;const q=clamp(p.t/p.duration,0,1),ease=q<.5?2*q*q:1-Math.pow(-2*q+2,2)/2;p.x+=(p.tx-p.x)*Math.min(1,dt*14);p.y=p.y+(p.ty-p.y)*Math.min(1,dt*14)-Math.sin(q*Math.PI)*70*dt*3;if(q>=1&&!p.done){this.explosion(p.tx,p.ty,p.splash,p.dmg,p.kind==='rocket');p.done=true}}}
 explosion(x,y,r,dmg,big=false){for(const e of [...this.state.enemies,...this.state.bosses]){const dd=Math.sqrt((e.x-x)**2+(e.y-y)**2);if(dd<r+e.radius)this.hit(e,dmg*(1-dd/(r+e.radius)*.45),0)}this.state.effects.push({type:'explosion',x,y,r,t:.35,color:big?'#ff7a4f':'#ffbd62'});this.audio.explosion(big)}
 updateEffects(dt){for(const e of this.state.effects){e.t-=dt;if(e.type==='danger'&&e.t<=0&&!e.done){this.explosion(e.x,e.y,e.r,e.damage,true);this.damageArmy(e.damage*.45);e.done=true}}}
 cleanup(){const s=this.state;for(const e of s.enemies){if(e.hp<=0&&!e.dead){e.dead=true;s.kills++;if(ENEMY_TYPES[e.type]?.split){for(let i=0;i<ENEMY_TYPES[e.type].split;i++)this.spawnEnemy('swarmer',e.x+this.rng.range(-18,18),e.y+this.rng.range(-10,10),.72)}if(s.mods.chainReaction&&e.burn>0)this.explosion(e.x,e.y,42,26*s.mods.damage,false);if(s.mods.killExplosion&&s.kills%s.mods.killExplosion===0)this.explosion(e.x,e.y,78,58*s.mods.damage,true);if(s.mods.armageddon&&s.kills%s.mods.armageddon===0){for(const a of s.enemies)this.hit(a,52*s.mods.damage,0);this.flash('ARMAGEDDON')}}}s.enemies=s.enemies.filter(e=>!e.dead&&e.hp>0&&e.y<this.h+60);for(const b of s.bosses){if(b.hp<=0&&!b.dead){b.dead=true;s.kills+=10;this.audio.explosion(true)}}s.bosses=s.bosses.filter(b=>!b.dead&&b.hp>0);const before=s.units.length;s.units=s.units.filter(u=>u.hp>0);s.deadTroops+=before-s.units.length;if(before>0&&s.units.length===0&&s.mods.lastStand&&!s.lastStandUsed){s.lastStandUsed=true;for(let i=0;i<Math.max(1,Math.floor(before*.25));i++)this.addUnit('rifleman');this.flash('LAST STAND')}s.projectiles=s.projectiles.filter(p=>!p.done);s.effects=s.effects.filter(e=>e.t>0);const ev=this.currentLevel().events[s.eventIndex];if(ev?.type==='boss'&&s.bosses.length===0&&s.enemies.length===0)this.advanceEvent()}
 useAbility(){const s=this.state;if(!this.running||this.paused||s.abilityCd>0)return;this.audio.ability();s.abilityCd=24;s.abilityActive=6;for(const u of s.units)u.hp=Math.min(u.maxHp,u.hp+u.maxHp*.08);this.flash('RALLY!')}
 togglePause(){if(!this.running||this.choiceOpen)return;this.paused=!this.paused;this.ui.togglePause(this.paused);if(!this.paused)this.last=performance.now()}
 flash(text){this.ui.flash(text)}
 win(){this.running=false;const elapsed=(performance.now()-this.state.startedAt)/1000;const reward=Math.round(70+this.levelIndex*24+this.state.kills*.8);this.ui.showResult(true,this,reward,elapsed)}
 lose(){if(!this.running)return;this.running=false;const elapsed=(performance.now()-this.state.startedAt)/1000;const reward=Math.round(20+this.state.kills*.25);this.ui.showResult(false,this,reward,elapsed)}
 progress(){const level=this.currentLevel();return clamp((this.state.eventIndex+(this.state.eventTime/Math.max(1,level.events[this.state.eventIndex]?.duration||1))*.7)/level.events.length,0,1)}
 render(){const c=this.ctx;c.clearRect(0,0,this.w,this.h);this.drawBackground(c);this.drawEffectsBack(c);for(const e of this.state.enemies)this.drawEnemy(c,e);for(const b of this.state.bosses)this.drawBoss(c,b);for(const p of this.state.projectiles)this.drawProjectile(c,p);for(const [i,u] of this.state.units.entries())this.drawUnit(c,u,i);this.drawEffectsFront(c)}
 drawBackground(c){const biome=this.currentLevel().biome;const palettes={city:['#0a1929','#12283c'],wasteland:['#211a18','#38281e'],hive:['#201020','#3a1530'],machine:['#0d1220','#141d35']};const [a,b]=palettes[biome]||palettes.city;const g=c.createLinearGradient(0,0,0,this.h);g.addColorStop(0,a);g.addColorStop(1,b);c.fillStyle=g;c.fillRect(0,0,this.w,this.h);c.strokeStyle='#ffffff0b';c.lineWidth=1;const laneW=Math.min(this.w*.72,720),left=(this.w-laneW)/2;c.fillStyle='#ffffff05';c.fillRect(left,0,laneW,this.h);for(let y=(this.state.time*45)%80-80;y<this.h;y+=80){c.beginPath();c.moveTo(left,y);c.lineTo(left+laneW,y);c.stroke()}c.strokeStyle='#55cfff18';c.beginPath();c.moveTo(left,0);c.lineTo(left,this.h);c.moveTo(left+laneW,0);c.lineTo(left+laneW,this.h);c.stroke()}
 drawUnit(c,u,i){const d=UNIT_TYPES[u.type];c.save();c.translate(u.x,u.y);c.fillStyle='#0006';c.beginPath();c.ellipse(0,7,8,4,0,0,Math.PI*2);c.fill();c.fillStyle=d.color;c.beginPath();c.arc(0,0,u.type==='shield'?8:6,0,Math.PI*2);c.fill();c.fillStyle='#dff7ff';c.fillRect(-2,-10,4,6);c.strokeStyle=d.color;c.lineWidth=u.type==='machinegun'?3:2;c.beginPath();c.moveTo(2,-4);c.lineTo(2,-14);c.stroke();if(u.type==='shield'){c.strokeStyle='#b9d7ff';c.lineWidth=3;c.beginPath();c.arc(0,-2,10,Math.PI,Math.PI*2);c.stroke()}c.restore()}
 drawEnemy(c,e){const d=ENEMY_TYPES[e.type];c.save();c.translate(e.x,e.y);c.fillStyle='#0005';c.beginPath();c.ellipse(0,7,e.radius,4,0,0,Math.PI*2);c.fill();c.fillStyle=d.color;c.beginPath();c.arc(0,0,e.radius,0,Math.PI*2);c.fill();if(e.burn>0){c.fillStyle='#ffb349';c.beginPath();c.arc(0,-e.radius*.5,e.radius*.45,0,Math.PI*2);c.fill()}if(d.armor)c.strokeStyle='#ffd0d2',c.lineWidth=2,c.stroke();c.restore()}
 drawBoss(c,b){if(b.hidden)return;const d=BOSSES[b.bossId];c.save();c.translate(b.x,b.y);c.fillStyle='#0008';c.beginPath();c.ellipse(0,b.radius*.55,b.radius*1.1,b.radius*.38,0,0,Math.PI*2);c.fill();c.fillStyle=d.color;c.beginPath();c.arc(0,0,b.radius,0,Math.PI*2);c.fill();c.strokeStyle='#ffd5dc';c.lineWidth=3;c.stroke();c.fillStyle='#0c1016';c.fillRect(-55,-b.radius-22,110,7);c.fillStyle='#ff4f63';c.fillRect(-55,-b.radius-22,110*Math.max(0,b.hp/b.maxHp),7);c.fillStyle='#fff';c.textAlign='center';c.font='700 9px system-ui';c.fillText(d.name,0,-b.radius-29);c.restore()}
 drawProjectile(c,p){c.fillStyle=p.color;c.beginPath();c.arc(p.x,p.y,p.kind==='rocket'?4:3,0,Math.PI*2);c.fill()}
 drawEffectsBack(c){for(const e of this.state.effects){if(e.type==='danger'){c.fillStyle='#ff344422';c.strokeStyle='#ff596caa';c.lineWidth=2;c.beginPath();c.arc(e.x,e.y,e.r,0,Math.PI*2);c.fill();c.stroke()}}}
 drawEffectsFront(c){for(const e of this.state.effects){if(e.type==='tracer'||e.type==='beam'){c.strokeStyle=e.color;c.globalAlpha=Math.min(1,e.t*10);c.lineWidth=e.type==='beam'?2.5:1.2;c.beginPath();c.moveTo(e.x,e.y);c.lineTo(e.x2,e.y2);c.stroke();c.globalAlpha=1}else if(e.type==='explosion'){c.fillStyle=e.color+'66';c.beginPath();c.arc(e.x,e.y,e.r*(1-e.t/.35*.4),0,Math.PI*2);c.fill()}else if(e.type==='ring'){c.strokeStyle=e.color;c.beginPath();c.arc(e.x,e.y,e.r,0,Math.PI*2);c.stroke()}}}
}
